---
- name: Verify
  hosts: all
  tasks:
  - name: check if dhcp is installed
    package:
      name: "dhcp-server"
      state: present
    register: stat_result
    failed_when: stat_result.changed
...