---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    docker_networks:
    - name: 'k3s'
      ipam_config:
        - subnet: '10.0.0.0/24'
    networks:
      - name: "k3s"
        ipv4_address: '10.0.0.3'
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
  - name: verify
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    docker_networks:
    - name: k3s
      ipam_config:
        - subnet: '10.0.0.0/24'
    networks:
      - name: k3s
        ipv4_address: '10.0.0.2'
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
...
