---
- name: Verify
  hosts: all
  tasks:
  - name: check if dhcp is installed
    package:
      name: "isc-dhcp-server"
      state: present
    register: stat_result
    failed_when: stat_result.changed

  - name: check if isc-dhcp-server is running
    service:
      name: isc-dhcp-server
      state: started
      enabled: true
    register: service_result
    failed_when: service_result.changed

  - name: Check if interface is set to eth0
    lineinfile:
      dest: /etc/default/isc-dhcp-server
      line: "INTERFACESv4=\"eth0\""
      regexp: '^INTERFACESv4='
    register: interface_result
    failed_when: interface_result.changed
...