---
name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  schedule:
    - cron: "30 8 * * 3"

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Clone all owned repos matching a filter
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python3 -m virtualenv .env
          source .env/bin/activate
          pip3 install -r requirements.txt
          molecule test --all
  merge:
    name: Merge to main
    runs-on: ubuntu-latest
    needs: 
      - linter
      - functional-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main

...